# SPDX-FileCopyrightText: 2025 Ivan Perevala <ivan95perevala@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html#manifest

schema_version = "1.0.0"

id = "multiple_camera_render"
version = "4.2.1"
name = "Multiple Camera Render (Development)"
tagline = "Development setup for multiple camera render"
maintainer = "Ivan Perevala <ivan95perevala@gmail.com>"
type = "add-on"
website = "https://multiple-camera-render.readthedocs.io/latest/"
tags = ["Render"]
blender_version_min = "4.2.0"

# NOTE: Current manifest should not contain `wheels` field. For development process, libraries should be installed
# manually (typically, using junction links to their code) - this way they can be modified alongside with extension.
#
# wheels = []

[permissions]
files = "Writing execution log files inside extension directory"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2020-2025 Ivan Perevala, Vladlen Kuzmin"]
