# SPDX-FileCopyrightText: 2025 Ivan Perevala <ivan95perevala@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html#manifest

schema_version = "1.0.0"

id = "test_handlers_conflict_from_lib"
version = "1.0.0"
name = "Test Handler Conflict From Library"
tagline = "Addon for testing handlers conflicts with Multiple Camera Render"
maintainer = "Ivan Perevala <ivan95perevala@gmail.com>"
type = "add-on"
tags = ["Development"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2020-2025 Ivan Perevala"]
wheels = [
    "wheels/lib_handlers_conflict-1.0.0-py3-none-any.whl"
]
