# SPDX-FileCopyrightText: 2025 Ivan Perevala <ivan95perevala@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html#manifest

schema_version = "1.0.0"

id = "multiple_camera_render"
version = "4.2.0"
name = "Multiple Camera Render"
tagline = "Sequential rendering from multiple cameras"
maintainer = "Ivan Perevala <ivan95perevala@gmail.com>"
type = "add-on"
website = "https://github.com/ivan-perevala/multiple_camera_render"
tags = ["Render", "Animation"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
wheels = [
    "wheels/bhqui-1.0.0-py3-none-any.whl",
    "wheels/bhqrprt-1.0.0-py3-none-any.whl",
    "wheels/bhqmain-1.0.0-py3-none-any.whl",
]
copyright = ["2020-2025 Ivan Perevala, Vladlen Kuzmin"]

[permissions]
files = "Writing execution log files inside extension directory"

[build]
paths_exclude_pattern = ["__pycache__/", "logs/*.txt", ".gitkeep"]
