# SPDX-FileCopyrightText: 2025 Ivan Perevala <ivan95perevala@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Blender 4.4.0
description: |
  This workflow tests the Blender extension for multiple camera rendering.

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
    types: [closed]

jobs:
  test-addon:
    runs-on: ubuntu-latest

    env:
      BLENDER_VERSION: "4.4.0"
      BLENDER_DIR: "${{ github.workspace }}/blender"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Blender
        id: cache-blender
        uses: actions/cache@v4
        with:
          path: ${{ env.BLENDER_DIR }}
          key: blender-${{ env.BLENDER_VERSION }}

      - name: Download Blender if not cached
        if: steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          BLENDER_MAJOR_MINOR=$(echo "${{ env.BLENDER_VERSION }}" | cut -d. -f1,2)
          DOWNLOAD_URL="https://download.blender.org/release/Blender${BLENDER_MAJOR_MINOR}/blender-${{ env.BLENDER_VERSION }}-linux-x64.tar.xz"

          mkdir -p "${{ env.BLENDER_DIR }}"
          wget -qO- "${DOWNLOAD_URL}" | tar -xJ --strip-components=1 -C "${{ env.BLENDER_DIR }}"
      
      - name: Get Blender Python executable
        run: |
          PYTHON_EXEC=$(blender --background --factory-startup --quiet --python-expr "import sys; print(sys.executable)")
          echo "BLENDER_PYTHON=$PYTHON_EXEC" >> $GITHUB_ENV

      - name: Install Python dependencies in Blender
        run: |
          $BLENDER_PYTHON -m ensurepip
          $BLENDER_PYTHON -m pip install --upgrade pip

          $BLENDER_PYTHON -m pip install pytest

      - name: Download wheels to build Multiple Camera Render
        run: |
          $BLENDER_PYTHON -m pip download -r requirements-dev.txt --dest "src/multiple_camera_render/wheels"

      - name: Build and install Multiple Camera Render
        run: |
          mkdir -p "${{ github.workspace }}/dist/multiple_camera_render"

          ${{ env.BLENDER_DIR }}/blender --command extension build --source-dir="./src/multiple_camera_render" --output-dir="./dist/multiple_camera_render"
          echo "Blender extension built successfully."
          EXTENSION_ZIP=$(find "./dist/multiple_camera_render" -type f -name "*.zip" | head -n 1)
          echo "Extension zip file: ${EXTENSION_ZIP}"
          "${{ env.BLENDER_DIR }}/blender" --command extension install-file --repo user_default --enable "${EXTENSION_ZIP}"

      - name: Run tests
        run: |
          $BLENDER_PYTHON -m pytest -k "test_conflicts" -s -v --blender="${{ env.BLENDER_DIR }}/blender" --repo user_default --background-only
