# SPDX-FileCopyrightText: 2026 Ivan Perevala <ivan95perevala@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build Extension
description: Build Blender extension and upload as artifact.

on:
  push:
    paths:
      - .github/workflows/build-extension.yml
      - icons/*.blend
      - icons/*.py
      - scripts/build.sh
      - src/multiple_camera_render/*
      - requirements.txt

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MCR_DISTRIBUTION_DIR: /home/mcr/multiple_camera_render
  MCR_ROOT_DIR: /home/mcr/multiple_camera_render

jobs:
  build_extension:
    name: Build Extension
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        MCR_ROOT_DIR: ${{ env.MCR_ROOT_DIR }}
        MCR_DISTRIBUTION_DIR: ${{ env.MCR_DISTRIBUTION_DIR }}
      volumes:
        - ${{ github.workspace }}:/${{ env.MCR_DISTRIBUTION_DIR }}

    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Build extension
        run: bash ./scripts/build.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: "${{ env.MCR_DISTRIBUTION_DIR }}/multiple_camera_render-*.zip"
          if-no-files-found: error
          overwrite: true
          archive: false
