# SPDX-FileCopyrightText: 2025 Ivan Perevala <ivan95perevala@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Spell Check
description: |
  This workflow runs codespell to check for spelling errors in the codebase.
  
on:
  pull_request:
  push:
    branches: [main]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: |
          codespell
